---
abstract: 'Use EPub as a target for EPublisher'
author:
  - 'Renee Bäcker <module@renee-baecker.de>, Boris Däppen <boris_daeppen@bluewin.ch>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EPublisher-Target-Plugin-EPub
requires:
  Data::UUID: 1.217
  EBook::EPUB: 0.6
  EPublisher: 0.6
  File::Basename: 2
  File::Temp: 0
  Pod::Simple::XHTML: 3.14
version: 0.11
